config/routes.rb
Rails.application.routes.draw do
  # Define a página inial da aplicação:
  root "events#index"

  # Define rotas para inscrições, apenas para criar e deletar:
  resources :subscriptions, only: %i[create destroy]
  # Define rotas para eventos - CRUD completo:
  resources :events

  # Define as rotas de login e registro de usuário:
  devise_for :users

  # Revela o status de saúde em /up que retorna 200 se o aplicativo inicializar sem exceções, caso contrário, retorna 500.
  # Pode ser usado por balanceadores de carga e monitores de disponibilidade para verificar se o aplicativo está ativo.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :subscriptions
  has_many :users, through: :subscriptions

  validates :name, :schedule, :location, presence: true

  def manager?(param_user)
    user.id == param_user.id
  end

  def subscribed?(param_user)
    subscriptions.exists?(user_id: param_user.id)
  end

  def find_subscription(param_user)
    subscriptions.find_by(user_id: param_user)
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events # manager
  has_many :subscriptions # attendee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  before_action :set_event, only: %i[ edit update destroy ]

  # GET /events or /events.json
  def index
    if params[:my_events].present?
      # Caso o parâmetro 'my_events' esteja presente, mostra apenas os eventos criados pelo usuário logado
      authenticate_user!
      @events = Event.where(user_id: current_user.id)
    elsif params[:subscribed].present?
      # Caso o parâmetro 'subscribed' esteja presente, mostra apenas os eventos inscritos pelo usuário logado
      authenticate_user!
      @events = Event.joins(:subscriptions).where(subscriptions: { user_id: current_user.id })
    else
      # Caso nenhum dos parâmetros acima esteja presente, mostra todos os eventos
      @events = Event
    end
    # Ordena os eventos filtrados baseado na data em que vão acontecer
    @events = @events.order(schedule: :asc).all
  end

  # GET /events/1 or /events/1.json
  def show
    # O 'preload' abaixo evita o problema de N+1 queries
    @event = Event.preload(:user).find(params[:id])
    @subscription = @event.find_subscription(current_user)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Evento foi criado com sucesso." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Evento foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: "Evento foi deletado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = current_user.events.preload(:user).find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :schedule, :location, :description)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_subscription, only: %i[ destroy ]

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = current_user.subscriptions.create!(event_id: subscription_params[:event_id])
    @event = Event.find(subscription_params[:event_id])

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @event, notice: "Inscrição foi criado com sucesso." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { redirect_to @event, notice: "Inscrição não foi criada." }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy!

    respond_to do |format|
      format.html { redirect_to @subscription.event, status: :see_other, notice: "Inscrição foi criada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    def set_subscription
      @subscription = current_user.subscriptions.find(params[:id])
    end

    def subscription_params
      params.require(:subscription).permit(:event_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Nome:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= event.schedule %>
  </p>

  <p>
    <strong>Localização:</strong>
    <%= event.location %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Organizador:</strong>
    <%= event.user.email %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2>Erros proibiram esse evento de ser salvo:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label 'Nome', style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label 'Data', style: "display: block" %>
    <%= form.datetime_field :schedule %>
  </div>

  <div>
    <%= form.label 'Localização', style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label 'Descrição', style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit('Criar evento') %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editando evento</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Ver evento", @event %> |
  <%= link_to "Voltar", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Eventos</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Ver esse evento", event %>
    </p>
  <% end %>
</div>

<%= link_to "Novo evento", new_event_path %>

app/views/events/new.html.erb
<h1>Novo evento</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Voltar", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <% if @event.manager?(current_user) %>
    <%= link_to "Editar esse evento", edit_event_path(@event) %> |
  <% end %>
  <%= link_to "Voltar", events_path %>

  <br><br>

  <% if @event.manager?(current_user) %>
    <%= button_to "Deletar esse evento", @event, method: :delete %>
    <br>
  <% end %>

  <% unless @subscription %>
    <%= button_to "Inscrever-se", subscriptions_path(
      subscription: { user_id: current_user.id, event_id: @event.id }
    ), method: :post %>
  <% end %>

  <% if @subscription %>
    <%= button_to "Cancelar inscrição", subscription_path(id: @subscription.id), method: :delete %>
  <% end %>
</div>

<hr>

<div>
  <h3>Usuários inscritos:</h3>
  <% @event.subscriptions.each do |subscription| %>
    <li>
      <%= subscription.user.email %>
    </li>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestãoDeEventos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
      <p>Usuário logado: <%= current_user.email %></p>
    <% end %>
    <%= link_to 'TodosEventos', root_path %>
    <%= link_to 'MeusEventos', events_path(my_events: true) %>
    <%= link_to 'EventosInscritos', events_path(subscribed: true) %>
    |
    <% if current_user %>
      <%= link_to 'Sair', destroy_user_session_path %>
    <% else %>
      <%= link_to 'Entrar', new_user_session_path %>
      <%= link_to 'Cadastrar-se', new_user_registration_path %>
    <% end %>
    <hr>

    <%= yield %>
  </body>
</html>